# fly.toml app configuration file generated for vivyver5 on 2023-07-03T16:51:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vivyver5"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
