# fly.toml file generated for vivyver4 on 2023-05-23T09:59:44+07:00

app = "vivyver4"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
